module.exports = {
  CreateObject: (product, bom_item) => {
    return {
      [`ExternalID`]: product.ProductCode,
      [`Item Name/Number`]: product.ProductCode,
      [`UPC Code`]: product.Barcode,
      [`Display Name/Code`]: product.Name,
      [`Vendor Name/Code`]: ``,
      [`Units Type `]: ``,
      [`Stock Units `]: ``,
      [`Purchase Units`]: ``,
      [`Sale Units`]: ``,
      [`Subitem Of`]: ``,
      [`Description`]: ``,
      [`Subsidiary`]: `Suavecito, Inc.`,
      [`Include Children`]: ``,
      [`Channel`]: ``,
      [`Product Category`]: ``,
      [`Location`]: ``,
      [`Item Image`]: ``,
      [`Season`]: ``,
      [`Style`]: ``,
      [`Department`]: ``,
      [`Close-Out`]: ``,
      [`Track Landed Cost`]: `TRUE`,
      [`Costing Method `]: `FIFO`,
      [`Cost Category`]: `INVENTORY`,
      [`Purchase Price`]: ``,
      [`Purchase Description`]: ``,
      [`Stock Descrption`]: ``,
      [`Match to Bill Receipt`]: ``,
      [`Use Bins`]: `TRUE`,
      [`Default ATP`]: ``,
      [`Replenishment Method`]: `Time Phased`,
      [`Alternate Source Item`]: ``,
      [`Auto-Calculate Preferred Stock Level`]: ``,
      [`Reorder Multiple`]: ``,
      [`Special Order Item`]: ``,
      [`Mark Sub-Assemblies Phantom`]: ``,
      [`Auto-Calculate Reorder Point`]: ``,
      [`Auto-Calculate Lead Time`]: `TRUE`,
      [`Lead Time`]: ``,
      [`Work Order Lead Time`]: ``,
      [`Safety Stock Level`]: ``,
      [`Safety Stock Level - Days`]: ``,
      [`Seasonal Demand`]: ``,
      [`Expected Demand Change`]: ``,
      [`Transfer Price`]: ``,
      [`Effective BOM Control`]: ``,
      [`Default Revision`]: ``,
      [`Round Up Quantity As Component`]: ``,
      [`Manufacturer`]: product.LastSuppliedBy,
      [`MPN`]: product.SupplierProductCode,
      [`Country of Manufacture`]: ``,
      [`Vendor Bill - Purchase Order Quantity Tolerance`]: ``,
      [`Vendor Bill - Purchase Order Amount Tolerance`]: ``,
      [`Vendor Bill - Purcahse Order Quantity Difference`]: ``,
      [`Vendor Bill - Item Receipt Quantity Tolerance`]: ``,
      [`Vendor Bill - Item Receipt Amount Tolerance`]: ``,
      [`Vendor Bill - Item Receipt Quantity Difference`]: ``,
      [`Preferred Location`]: ``,
      [`Item Bin Number 1`]: ``,
      [`Vendor 1 Name`]: ``,
      [`Vendor 1 Subsidiary`]: ``,
      [`Vendor 1 Preferred`]: ``,
      [`Vendor 1 Purchase Price`]: ``,
      [`Vendor 1 Schedule`]: ``,
      [`Vendor 1 Code`]: ``,
      [`Preferred (per Location)`]: ``,
      [`Item Location 1 Location`]: ``,
      [`Location 1 ATP Lead Time`]: ``,
      [`Location 1 Backward Consumption Days`]: ``,
      [`Location 1 Default Return Cost`]: ``,
      [`Location 1 Demand Source`]: ``,
      [`Item Location 1 Demand Time Fence`]: ``,
      [`Item Location 1 Fixed Lot Size`]: ``,
      [`Item Location 1 Forward Consumption Days`]: ``,
      [`Item Location 1 Periods of Supply Increment`]: ``,
      [`Item Location 1 Periods of Supply Type`]: ``,
      [`Item Location 1 Preferred Stock Level`]: ``,
      [`Item Location 1 Reorder Point`]: ``,
      [`Item Location 1 Reschedule in Days`]: ``,
      [`Item Location 1 Reschedule Out Days`]: ``,
      [`Item Location 1 Lot Sizing Method`]: ``,
      [`Item Location 1 Planning Time Fence`]: ``,
      [`Component 1 - Item`]: bom_item.ComponentSKU,
      [`Component 1 - Quantity`]: bom_item.Quantity,
      [`Component 2 - Item`]: ``,
      [`Component 2 - Quantity`]: ``,
      [`Component 3 - Item`]: ``,
      [`Component 3 - Quantity`]: ``,
      [`Component 4 - Item`]: ``,
      [`Component 4 - Quantity`]: ``,
      [`Component 5 - Item`]: ``,
      [`Component 5 - Quantity`]: ``,
      [`Component 6 - Item`]: ``,
      [`Component 6 - Quantity`]: ``,
      [`Component 7 - Item`]: ``,
      [`Component 7 - Quantity`]: ``,
      [`Component 8 - Item`]: ``,
      [`Component 8 - Quantity`]: ``,
      [`Component 9 - Item`]: ``,
      [`Component 9 - Quantity`]: ``,
      [`Component 10 - Item`]: ``,
      [`Component 10 - Quantity`]: ``,
      [`Component 11 - Item`]: ``,
      [`Component 11 - Quantity`]: ``,
      [`Component 12 - Item`]: ``,
      [`Component 12 - Quantity`]: ``,
      [`Component 13 - Item`]: ``,
      [`Component 13 - Quantity`]: ``,
      [`Component 14 - Item`]: ``,
      [`Component 14 - Quantity`]: ``,
      [`Component 15 - Item`]: ``,
      [`Component 15 - Quantity`]: ``,
      [`Component 16 - Item`]: ``,
      [`Component 16 - Quantity`]: ``,
      [`Component 17 - Item`]: ``,
      [`Component 17 - Quantity`]: ``,
      [`Component 18 - Item`]: ``,
      [`Component 18 - Quantity`]: ``,
      [`Component 19 - Item`]: ``,
      [`Component 19 - Quantity`]: ``,
      [`Component 20 - Item`]: ``,
      [`Component 20 - Quantity`]: ``,
      [`Component 21 - Item`]: ``,
      [`Component 21 - Quantity`]: ``,
      [`Component 22 - Item`]: ``,
      [`Component 22 - Quantity`]: ``,
      [`Component 23 - Item`]: ``,
      [`Component 23 - Quantity`]: ``,
      [`Component 24 - Item`]: ``,
      [`Component 24 - Quantity`]: ``,
      [`Component 25 - Item`]: ``,
      [`Component 25 - Quantity`]: ``,
      [`Component 26 - Item`]: ``,
      [`Component 26 - Quantity`]: ``,
      [`Component 27 - Item`]: ``,
      [`Component 27 - Quantity`]: ``,
      [`Component 28 - Item`]: ``,
      [`Component 28 - Quantity`]: ``,
      [`Component 29 - Item`]: ``,
      [`Component 29 - Quantity`]: ``,
      [`Component 30 - Item`]: ``,
      [`Component 30 - Quantity`]: ``,
      [`Sales Description`]: ``,
      [`Cost Estimate Type`]: `Average Cost`,
      [`Item Defined Cost`]: ``,
      [`Soft Descriptor`]: ``,
      [`Minimum Quantity`]: ``,
      [`Enforce Internally`]: ``,
      [`Item Weight`]: product.Weight,
      [`Weight Unit`]: product.WeightUnits,
      [`Quantity Pricing Schedule`]: ``,
      [`Use Marginal Rates`]: ``,
      [`Calculate Quantity Discounts`]: ``,
      [`Pricing Group`]: ``,
      [`Base Price`]: ``,
      [`Price Level (Req)`]: ``,
      [`Currency (Req)`]: ``,
      [`Price (Req)`]: ``,
      [`Quantity`]: ``,
      [`Price Level (Req)`]: ``,
      [`Currency (Req)`]: ``,
      [`Price (Req)`]: ``,
      [`Quantity`]: ``,
      [`Price Level (Req)`]: ``,
      [`Currency (Req)`]: ``,
      [`Price (Req)`]: ``,
      [`Quantity`]: ``,
      [`COGS Account`]: ``,
      [`Income Account `]: ``,
      [`Asset Account`]: ``,
      [`Bill Price Variance Account`]: ``,
      [`Bill Quantity Variance Account`]: ``,
      [`Bill Exchange Variance Rate Variance Account`]: ``,
      [`Customer Return Variance Account`]: ``,
      [`Vendor Return Variance Account`]: ``,
      [`Unbuild Variance Account`]: ``,
      [`Tax Schedule`]: `Taxable`,
      [`Available to Adv. Partners`]: ``,
      [`Offer Support`]: ``,
      [`Inactive`]: ``,
      [`Class`]: product.Category,
      [`Retail`]: product.PriceTier1,
      [`Wholesale`]: product.PriceTier2
    }
  },
  ObjectHeader: [
    { id: `ExternalID`, title: `ExternalID` },
    { id: `Item Name/Number`, title: `Item Name/Number` },
    { id: `UPC Code`, title: `UPC Code` },
    { id: `Display Name/Code`, title: `Display Name/Code` },
    { id: `Vendor Name/Code`, title: `Vendor Name/Code` },
    { id: `Units Type `, title: `Units Type ` },
    { id: `Stock Units `, title: `Stock Units ` },
    { id: `Purchase Units`, title: `Purchase Units` },
    { id: `Sale Units`, title: `Sale Units` },
    { id: `Subitem Of`, title: `Subitem Of` },
    { id: `Description`, title: `Description` },
    { id: `Subsidiary`, title: `Subsidiary` },
    { id: `Include Children`, title: `Include Children` },
    { id: `Channel`, title: `Channel` },
    { id: `Product Category`, title: `Product Category` },
    { id: `Location`, title: `Location` },
    { id: `Item Image`, title: `Item Image` },
    { id: `Season`, title: `Season` },
    { id: `Style`, title: `Style` },
    { id: `Department`, title: `Department` },
    { id: `Close-Out`, title: `Close-Out` },
    { id: `Track Landed Cost`, title: `Track Landed Cost` },
    { id: `Costing Method `, title: `Costing Method ` },
    { id: `Cost Category`, title: `Cost Category` },
    { id: `Purchase Price`, title: `Purchase Price` },
    { id: `Purchase Description`, title: `Purchase Description` },
    { id: `Stock Descrption`, title: `Stock Descrption` },
    { id: `Match to Bill Receipt`, title: `Match to Bill Receipt` },
    { id: `Use Bins`, title: `Use Bins` },
    { id: `Default ATP`, title: `Default ATP` },
    { id: `Replenishment Method`, title: `Replenishment Method` },
    { id: `Alternate Source Item`, title: `Alternate Source Item` },
    { id: `Auto-Calculate Preferred Stock Level`, title: `Auto-Calculate Preferred Stock Level` },
    { id: `Reorder Multiple`, title: `Reorder Multiple` },
    { id: `Special Order Item`, title: `Special Order Item` },
    { id: `Mark Sub-Assemblies Phantom`, title: `Mark Sub-Assemblies Phantom` },
    { id: `Auto-Calculate Reorder Point`, title: `Auto-Calculate Reorder Point` },
    { id: `Auto-Calculate Lead Time`, title: `Auto-Calculate Lead Time` },
    { id: `Lead Time`, title: `Lead Time` },
    { id: `Work Order Lead Time`, title: `Work Order Lead Time` },
    { id: `Safety Stock Level`, title: `Safety Stock Level` },
    { id: `Safety Stock Level - Days`, title: `Safety Stock Level - Days` },
    { id: `Seasonal Demand`, title: `Seasonal Demand` },
    { id: `Expected Demand Change`, title: `Expected Demand Change` },
    { id: `Transfer Price`, title: `Transfer Price` },
    { id: `Effective BOM Control`, title: `Effective BOM Control` },
    { id: `Default Revision`, title: `Default Revision` },
    { id: `Round Up Quantity As Component`, title: `Round Up Quantity As Component` },
    { id: `Manufacturer`, title: `Manufacturer` },
    { id: `MPN`, title: `MPN` },
    { id: `Country of Manufacture`, title: `Country of Manufacture` },
    { id: `Vendor Bill - Purchase Order Quantity Tolerance`, title: `Vendor Bill - Purchase Order Quantity Tolerance` },
    { id: `Vendor Bill - Purchase Order Amount Tolerance`, title: `Vendor Bill - Purchase Order Amount Tolerance` },
    { id: `Vendor Bill - Purcahse Order Quantity Difference`, title: `Vendor Bill - Purcahse Order Quantity Difference` },
    { id: `Vendor Bill - Item Receipt Quantity Tolerance`, title: `Vendor Bill - Item Receipt Quantity Tolerance` },
    { id: `Vendor Bill - Item Receipt Amount Tolerance`, title: `Vendor Bill - Item Receipt Amount Tolerance` },
    { id: `Vendor Bill - Item Receipt Quantity Difference`, title: `Vendor Bill - Item Receipt Quantity Difference` },
    { id: `Preferred Location`, title: `Preferred Location` },
    { id: `Item Bin Number 1`, title: `Item Bin Number 1` },
    { id: `Vendor 1 Name`, title: `Vendor 1 Name` },
    { id: `Vendor 1 Subsidiary`, title: `Vendor 1 Subsidiary` },
    { id: `Vendor 1 Preferred`, title: `Vendor 1 Preferred` },
    { id: `Vendor 1 Purchase Price`, title: `Vendor 1 Purchase Price` },
    { id: `Vendor 1 Schedule`, title: `Vendor 1 Schedule` },
    { id: `Vendor 1 Code`, title: `Vendor 1 Code` },
    { id: `Preferred (per Location)`, title: `Preferred (per Location)` },
    { id: `Item Location 1 Location`, title: `Item Location 1 Location` },
    { id: `Location 1 ATP Lead Time`, title: `Location 1 ATP Lead Time` },
    { id: `Location 1 Backward Consumption Days`, title: `Location 1 Backward Consumption Days` },
    { id: `Location 1 Default Return Cost`, title: `Location 1 Default Return Cost` },
    { id: `Location 1 Demand Source`, title: `Location 1 Demand Source` },
    { id: `Item Location 1 Demand Time Fence`, title: `Item Location 1 Demand Time Fence` },
    { id: `Item Location 1 Fixed Lot Size`, title: `Item Location 1 Fixed Lot Size` },
    { id: `Item Location 1 Forward Consumption Days`, title: `Item Location 1 Forward Consumption Days` },
    { id: `Item Location 1 Periods of Supply Increment`, title: `Item Location 1 Periods of Supply Increment` },
    { id: `Item Location 1 Periods of Supply Type`, title: `Item Location 1 Periods of Supply Type` },
    { id: `Item Location 1 Preferred Stock Level`, title: `Item Location 1 Preferred Stock Level` },
    { id: `Item Location 1 Reorder Point`, title: `Item Location 1 Reorder Point` },
    { id: `Item Location 1 Reschedule in Days`, title: `Item Location 1 Reschedule in Days` },
    { id: `Item Location 1 Reschedule Out Days`, title: `Item Location 1 Reschedule Out Days` },
    { id: `Item Location 1 Lot Sizing Method`, title: `Item Location 1 Lot Sizing Method` },
    { id: `Item Location 1 Planning Time Fence`, title: `Item Location 1 Planning Time Fence` },
    { id: `Component 1 - Item`, title: `Component 1 - Item` },
    { id: `Component 1 - Quantity`, title: `Component 1 - Quantity` },
    { id: `Component 2 - Item`, title: `Component 2 - Item` },
    { id: `Component 2 - Quantity`, title: `Component 2 - Quantity` },
    { id: `Component 3 - Item`, title: `Component 3 - Item` },
    { id: `Component 3 - Quantity`, title: `Component 3 - Quantity` },
    { id: `Component 4 - Item`, title: `Component 4 - Item` },
    { id: `Component 4 - Quantity`, title: `Component 4 - Quantity` },
    { id: `Component 5 - Item`, title: `Component 5 - Item` },
    { id: `Component 5 - Quantity`, title: `Component 5 - Quantity` },
    { id: `Component 6 - Item`, title: `Component 6 - Item` },
    { id: `Component 6 - Quantity`, title: `Component 6 - Quantity` },
    { id: `Component 7 - Item`, title: `Component 7 - Item` },
    { id: `Component 7 - Quantity`, title: `Component 7 - Quantity` },
    { id: `Component 8 - Item`, title: `Component 8 - Item` },
    { id: `Component 8 - Quantity`, title: `Component 8 - Quantity` },
    { id: `Component 9 - Item`, title: `Component 9 - Item` },
    { id: `Component 9 - Quantity`, title: `Component 9 - Quantity` },
    { id: `Component 10 - Item`, title: `Component 10 - Item` },
    { id: `Component 10 - Quantity`, title: `Component 10 - Quantity` },
    { id: `Component 11 - Item`, title: `Component 11 - Item` },
    { id: `Component 11 - Quantity`, title: `Component 11 - Quantity` },
    { id: `Component 12 - Item`, title: `Component 12 - Item` },
    { id: `Component 12 - Quantity`, title: `Component 12 - Quantity` },
    { id: `Component 13 - Item`, title: `Component 13 - Item` },
    { id: `Component 13 - Quantity`, title: `Component 13 - Quantity` },
    { id: `Component 14 - Item`, title: `Component 14 - Item` },
    { id: `Component 14 - Quantity`, title: `Component 14 - Quantity` },
    { id: `Component 15 - Item`, title: `Component 15 - Item` },
    { id: `Component 15 - Quantity`, title: `Component 15 - Quantity` },
    { id: `Component 16 - Item`, title: `Component 16 - Item` },
    { id: `Component 16 - Quantity`, title: `Component 16 - Quantity` },
    { id: `Component 17 - Item`, title: `Component 17 - Item` },
    { id: `Component 17 - Quantity`, title: `Component 17 - Quantity` },
    { id: `Component 18 - Item`, title: `Component 18 - Item` },
    { id: `Component 18 - Quantity`, title: `Component 18 - Quantity` },
    { id: `Component 19 - Item`, title: `Component 19 - Item` },
    { id: `Component 19 - Quantity`, title: `Component 19 - Quantity` },
    { id: `Component 20 - Item`, title: `Component 20 - Item` },
    { id: `Component 20 - Quantity`, title: `Component 20 - Quantity` },
    { id: `Component 21 - Item`, title: `Component 21 - Item` },
    { id: `Component 21 - Quantity`, title: `Component 21 - Quantity` },
    { id: `Component 22 - Item`, title: `Component 22 - Item` },
    { id: `Component 22 - Quantity`, title: `Component 22 - Quantity` },
    { id: `Component 23 - Item`, title: `Component 23 - Item` },
    { id: `Component 23 - Quantity`, title: `Component 23 - Quantity` },
    { id: `Component 24 - Item`, title: `Component 24 - Item` },
    { id: `Component 24 - Quantity`, title: `Component 24 - Quantity` },
    { id: `Component 25 - Item`, title: `Component 25 - Item` },
    { id: `Component 25 - Quantity`, title: `Component 25 - Quantity` },
    { id: `Component 26 - Item`, title: `Component 26 - Item` },
    { id: `Component 26 - Quantity`, title: `Component 26 - Quantity` },
    { id: `Component 27 - Item`, title: `Component 27 - Item` },
    { id: `Component 27 - Quantity`, title: `Component 27 - Quantity` },
    { id: `Component 28 - Item`, title: `Component 28 - Item` },
    { id: `Component 28 - Quantity`, title: `Component 28 - Quantity` },
    { id: `Component 29 - Item`, title: `Component 29 - Item` },
    { id: `Component 29 - Quantity`, title: `Component 29 - Quantity` },
    { id: `Component 30 - Item`, title: `Component 30 - Item` },
    { id: `Component 30 - Quantity`, title: `Component 30 - Quantity` },
    { id: `Sales Description`, title: `Sales Description` },
    { id: `Cost Estimate Type`, title: `Cost Estimate Type` },
    { id: `Item Defined Cost`, title: `Item Defined Cost` },
    { id: `Soft Descriptor`, title: `Soft Descriptor` },
    { id: `Minimum Quantity`, title: `Minimum Quantity` },
    { id: `Enforce Internally`, title: `Enforce Internally` },
    { id: `Item Weight`, title: `Item Weight` },
    { id: `Weight Unit`, title: `Weight Unit` },
    { id: `Quantity Pricing Schedule`, title: `Quantity Pricing Schedule` },
    { id: `Use Marginal Rates`, title: `Use Marginal Rates` },
    { id: `Calculate Quantity Discounts`, title: `Calculate Quantity Discounts` },
    { id: `Pricing Group`, title: `Pricing Group` },
    { id: `Base Price`, title: `Base Price` },
    { id: `Price Level (Req)`, title: `Price Level (Req)` },
    { id: `Currency (Req)`, title: `Currency (Req)` },
    { id: `Price (Req)`, title: `Price (Req)` },
    { id: `Quantity`, title: `Quantity` },
    { id: `Price Level (Req)`, title: `Price Level (Req)` },
    { id: `Currency (Req)`, title: `Currency (Req)` },
    { id: `Price (Req)`, title: `Price (Req)` },
    { id: `Quantity`, title: `Quantity` },
    { id: `Price Level (Req)`, title: `Price Level (Req)` },
    { id: `Currency (Req)`, title: `Currency (Req)` },
    { id: `Price (Req)`, title: `Price (Req)` },
    { id: `Quantity`, title: `Quantity` },
    { id: `COGS Account`, title: `COGS Account` },
    { id: `Income Account `, title: `Income Account ` },
    { id: `Asset Account`, title: `Asset Account` },
    { id: `Bill Price Variance Account`, title: `Bill Price Variance Account` },
    { id: `Bill Quantity Variance Account`, title: `Bill Quantity Variance Account` },
    { id: `Bill Exchange Variance Rate Variance Account`, title: `Bill Exchange Variance Rate Variance Account` },
    { id: `Customer Return Variance Account`, title: `Customer Return Variance Account` },
    { id: `Vendor Return Variance Account`, title: `Vendor Return Variance Account` },
    { id: `Unbuild Variance Account`, title: `Unbuild Variance Account` },
    { id: `Tax Schedule`, title: `Tax Schedule` },
    { id: `Available to Adv. Partners`, title: `Available to Adv. Partners` },
    { id: `Offer Support`, title: `Offer Support` },
    { id: `Inactive`, title: `Inactive` },
    { id: `Class`, title: `Class` },
    { id: `Retail`, title: `Retail` },
    { id: `Wholesale`, title: `Wholesale` }
  ],
  ReturnObject: (dear_inventory_item, shopify_retail_items, shopify_wholesale_items) => {
    const key = dear_inventory_item.ProductCode;
    const sri = shopify_retail_items;
    const swi = shopify_wholesale_items;
    return {
      [`ExternalID`]: dear_inventory_item.ProductCode,
      [`Item Name/Number`]: dear_inventory_item.ProductCode,
      [`Display Name/Code`]: dear_inventory_item.Name,
      [`Vendor SKU`]: dear_inventory_item.SupplierProductCode,
      [`Subsidiary`]: `Suavecito, Inc.`,
      [`Class`]: dear_inventory_item.Category,
      [`Track Landed Cost`]: `TRUE`,
      [`Costing Method `]: `FIFO`,
      [`Cost Category`]: `INVENTORY`,
      [`Use Bins`]: `TRUE`,
      [`Default ATP`]: ``,
      [`Replenishment Method`]: `Time Phased`,
      [`Auto-Calculate Lead Time`]: `TRUE`,
      [`Manufacturer`]: dear_inventory_item.LastSuppliedBy,
      [`MPN`]: dear_inventory_item.SupplierProductCode,
      [`Vendor 1 Name`]: dear_inventory_item.LastSuppliedBy,
      [`Cost Estimate Type`]: `Average Cost`,
      [`Item Weight`]: dear_inventory_item.Weight,
      [`Weight Unit`]: dear_inventory_item.WeightUnits,
      [`Tax Schedule`]: `Taxable`,
      [`UPC Code`]: dear_inventory_item.Barcode,
      [`Shopify Wholesale Product Handle`]: swi[key] ? swi[key][`Handle`] : ``,
      [`Shopify Wholesale Published Scope`]: swi[key] ? swi[key][`Published`] : ``,
      [`Shopify Wholesale Price`]: swi[key] ? swi[key][`Variant Price`] : ``,
      [`Shopify Wholesale Compare At Price`]: swi[key] ? swi[key][`Variant Compare At Price`] : ``,
      [`Shopify Wholesale Description`]: swi[key] ? swi[key][`Body (HTML)`] : ``,
      [`Shopify Wholesale Tags`]: swi[key] ? swi[key][`Tags`] : ``,
      [`Shopify Retail Product Handle`]: sri[key] ? swi[key][`Handle`] : ``,
      [`Shopify Retail Published Scope`]: sri[key] ? swi[key][`Published`] : ``,
      [`Shopify Retail Price`]: sri[key] ? sri[key][`Variant Price`] : ``,
      [`Shopify Retail Compare At Price`]: sri[key] ? swi[key][`Variant Compare At Price`] : ``,
      [`Shopify Retail Description`]: sri[key] ? swi[key][`Body (HTML)`] : ``,
      [`Shopify Retail Tags`]: sri[key] ? swi[key][`Tags`] : ``,
      [`Shopify Product Type`]: sri[key] ? sri[key][`Type`] : swi[key] ? swi[key][`Type`] : ``,
      [`Shopify Requires Shipping`]: `TRUE`
    }
  },
  FormatShopifyObject: (file) => {
    const object = {};
    for(let i = 0; i < file.length; i++) {
      object[file[i][`Variant SKU`]] = file[i];
    }
    return object;
  },
  Headers: [
    { id: `ExternalID`, title: `ExternalID` },
    { id: `Item Name/Number`, title: `Item Name/Number` },
    { id: `Display Name/Code`, title: `Display Name/Code` },
    { id: `Vendor SKU`, title: `Vendor SKU` },
    { id: `Subsidiary`, title: `Subsidiary` },
    { id: `Class`, title: `Class` },
    { id: `Track Landed Cost`, title: `Track Landed Cost` },
    { id: `Costing Method `, title: `Costing Method ` },
    { id: `Cost Category`, title: `Cost Category` },
    { id: `Use Bins`, title: `Use Bins` },
    { id: `Default ATP`, title: `Default ATP` },
    { id: `Replenishment Method`, title: `Replenishment Method` },
    { id: `Auto-Calculate Lead Time`, title: `Auto-Calculate Lead Time` },
    { id: `Manufacturer`, title: `Manufacturer` },
    { id: `MPN`, title: `MPN` },
    { id: `Vendor 1 Name`, title: `Vendor 1 Name` },
    { id: `Cost Estimate Type`, title: `Cost Estimate Type` },
    { id: `Item Weight`, title: `Item Weight` },
    { id: `Weight Unit`, title: `Weight Unit` },
    { id: `Tax Schedule`, title: `Tax Schedule` },
    { id: `UPC Code`, title: `UPC Code` },
    { id: `Shopify Wholesale Product Handle`, title: `Shopify Wholesale Product Handle` },
    { id: `Shopify Wholesale Published Scope`, title: `Shopify Wholesale Published Scope` },
    { id: `Shopify Wholesale Price`, title: `Shopify Wholesale Price` },
    { id: `Shopify Wholesale Compare At Price`, title: `Shopify Wholesale Compare At Price` },
    { id: `Shopify Wholesale Description`, title: `Shopify Wholesale Description` },
    { id: `Shopify Wholesale Tags`, title: `Shopify Wholesale Tags` },
    { id: `Shopify Retail Product Handle`, title: `Shopify Retail Product Handle` },
    { id: `Shopify Retail Published Scope`, title: `Shopify Retail Published Scope` },
    { id: `Shopify Retail Price`, title: `Shopify Retail Price` },
    { id: `Shopify Retail Compare At Price`, title: `Shopify Retail Compare At Price` },
    { id: `Shopify Retail Description`, title: `Shopify Retail Description` },
    { id: `Shopify Retail Tags`, title: `Shopify Retail Tags` },
    { id: `Shopify Product Type`, title: `Shopify Product Type` },
    { id: `Shopify Requires Shipping`, title: `Shopify Requires Shipping` },
    { id: `Component 1 - Item`, title: `Component 1 - Item` },
    { id: `Component 1 - Quantity`, title: `Component 1 - Quantity` },
    { id: `Component 2 - Item`, title: `Component 2 - Item` },
    { id: `Component 2 - Quantity`, title: `Component 2 - Quantity` },
    { id: `Component 3 - Item`, title: `Component 3 - Item` },
    { id: `Component 3 - Quantity`, title: `Component 3 - Quantity` },
    { id: `Component 4 - Item`, title: `Component 4 - Item` },
    { id: `Component 4 - Quantity`, title: `Component 4 - Quantity` },
    { id: `Component 5 - Item`, title: `Component 5 - Item` },
    { id: `Component 5 - Quantity`, title: `Component 5 - Quantity` },
    { id: `Component 6 - Item`, title: `Component 6 - Item` },
    { id: `Component 6 - Quantity`, title: `Component 6 - Quantity` },
    { id: `Component 7 - Item`, title: `Component 7 - Item` },
    { id: `Component 7 - Quantity`, title: `Component 7 - Quantity` },
    { id: `Component 8 - Item`, title: `Component 8 - Item` },
    { id: `Component 8 - Quantity`, title: `Component 8 - Quantity` },
    { id: `Component 9 - Item`, title: `Component 9 - Item` },
    { id: `Component 9 - Quantity`, title: `Component 9 - Quantity` },
    { id: `Component 10 - Item`, title: `Component 10 - Item` },
    { id: `Component 10 - Quantity`, title: `Component 10 - Quantity` },
    { id: `Component 11 - Item`, title: `Component 11 - Item` },
    { id: `Component 11 - Quantity`, title: `Component 11 - Quantity` },
    { id: `Component 12 - Item`, title: `Component 12 - Item` },
    { id: `Component 12 - Quantity`, title: `Component 12 - Quantity` },
    { id: `Component 13 - Item`, title: `Component 13 - Item` },
    { id: `Component 13 - Quantity`, title: `Component 13 - Quantity` },
    { id: `Component 14 - Item`, title: `Component 14 - Item` },
    { id: `Component 14 - Quantity`, title: `Component 14 - Quantity` },
    { id: `Component 15 - Item`, title: `Component 15 - Item` },
    { id: `Component 15 - Quantity`, title: `Component 15 - Quantity` },
    { id: `Component 16 - Item`, title: `Component 16 - Item` },
    { id: `Component 16 - Quantity`, title: `Component 16 - Quantity` },
    { id: `Component 17 - Item`, title: `Component 17 - Item` },
    { id: `Component 17 - Quantity`, title: `Component 17 - Quantity` },
    { id: `Component 18 - Item`, title: `Component 18 - Item` },
    { id: `Component 18 - Quantity`, title: `Component 18 - Quantity` },
    { id: `Component 19 - Item`, title: `Component 19 - Item` },
    { id: `Component 19 - Quantity`, title: `Component 19 - Quantity` },
    { id: `Component 20 - Item`, title: `Component 20 - Item` },
    { id: `Component 20 - Quantity`, title: `Component 20 - Quantity` },
    { id: `Component 21 - Item`, title: `Component 21 - Item` },
    { id: `Component 21 - Quantity`, title: `Component 21 - Quantity` },
    { id: `Component 22 - Item`, title: `Component 22 - Item` },
    { id: `Component 22 - Quantity`, title: `Component 22 - Quantity` },
    { id: `Component 23 - Item`, title: `Component 23 - Item` },
    { id: `Component 23 - Quantity`, title: `Component 23 - Quantity` },
    { id: `Component 24 - Item`, title: `Component 24 - Item` },
    { id: `Component 24 - Quantity`, title: `Component 24 - Quantity` },
    { id: `Component 25 - Item`, title: `Component 25 - Item` },
    { id: `Component 25 - Quantity`, title: `Component 25 - Quantity` },
    { id: `Component 26 - Item`, title: `Component 26 - Item` },
    { id: `Component 26 - Quantity`, title: `Component 26 - Quantity` },
    { id: `Component 27 - Item`, title: `Component 27 - Item` },
    { id: `Component 27 - Quantity`, title: `Component 27 - Quantity` },
    { id: `Component 28 - Item`, title: `Component 28 - Item` },
    { id: `Component 28 - Quantity`, title: `Component 28 - Quantity` },
    { id: `Component 29 - Item`, title: `Component 29 - Item` },
    { id: `Component 29 - Quantity`, title: `Component 29 - Quantity` },
    { id: `Component 30 - Item`, title: `Component 30 - Item` },
    { id: `Component 30 - Quantity`, title: `Component 30 - Quantity` }
  ]
}